name: Deploy Lambda

on:
  push:
    branches: main
    paths: backend/*

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Zip Lambda
      run: zip -j function.zip backend/lambda_function.py

    - name: Upload to Lambda
      run: |
        aws lambda update-function-code \
          --function-name ViewerCounter \
          --zip-file fileb://function.zip \
          --region ap-southeast-2
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}